#!/usr/bin/bash
code=0
ASM='s'
EXE='.exe'
if [ $# -eq 0 ];
then
  cowsay -d No source file specified
  echo
  exit 1
fi
f=$1

# Removes any extensions or periods that may have been added.
f=$(echo $f | sed 's/\.[^.]*$//')

echo "File is $f"

source="$f.$ASM"
echo "Processing $f as $source"
if [ -f $f.o ]; then rm $f.o; fi
if [ -f $f.lst ]; then rm $f.lst; fi
if [ -f $f.exe ]; then rm $f.exe; fi

clear
if [ -f $source ];
  then
     echo "Processing $f.$ASM"
  else
     echo "Did not find $f.$ASM.  ABORTING"
     exit 1
fi

object=$f.o
if [ -f $source ]; 
then
  gcc -g  -Wa,-al  -o $f.exe   $source > $f.lst 2>&1
  code=$?
  if [ $code -ne 0 ];then
     echo "Assembler ended with error code $code" | lolcat
  fi 
  if [ -f $f.lst ]; then cat $f.lst; fi
  if [ -f $f$EXE ]; then
   echo "Compile and link successful"
   echo "Running..................."
   ./$f$EXE  
   echo ".........................."
   code=$?
   echo "Exit code for the program is $code" | lolcat
   # The following was added todemonstrate printf.   I suggest you remove it.
   printf "The exit code for the program is %d\n" $code  | lolcat
  fi
fi
echo DONE
exit $code
