#!/usr/bin/bash
code=0
ASM='s'
EXE='.exe'
if [ $# -eq 0 ];
then
  cowsay -d No source file specified
  echo
  exit 1
fi
f=$1

source="$f.$ASM"
echo "Processing $f as $source"
if [ -f $f.o ]; then rm $f.o; fi
if [ -f $f.lst ]; then rm $f.lst; fi
if [ -f $f ]; then rm $f; fi

if [ -f $source ];
  then
     echo "Processing $f.$ASM"
  else
     echo "Did not find $f.$ASM.  ABORTING"
     exit 1
fi

object=$f.o
if [ -f $source ]; 
then
  as -al=$f.lst -o $object  $source
  code=$?
  if [ $code -ne 0 ];then
     echo "Assembler ended with error code $code" | lolcat
  fi 
  if [ -f $f.lst ]; then cat $f.lst; fi
  if [ -f $object ]; then ld -o $f$EXE $object; fi
  code=$?
  if [ $code -ne 0 ];then
     echo "Linker ended with error code $code" | lolcat
  fi 
  if [ -f $f$EXE ]; then
   echo "Compile and link successful"
   echo "Running..."
   ./$f$EXE
   code=$?
   echo "Exit code for the program is $code" | lolcat
  fi
fi
echo DONE
exit $code
